### ISSUE TITLE
teuthology.provision.openstack does not handle server creation error correctly

### ISSUE THREAD

**Issue by kshtsk** [SUSE/teuthology#104]
Issue happens after exhausting of tries to get ip while trying to create a worker and when a server instance exists and have _ERROR_ status.

`Failure Reason` example:

`'get ip 7805cbf2-6ade-4d21-9486-d36e067e20a9' reached maximum tries (30) after waiting for 60 seconds`

`2017-10-12T14:21:26.545 DEBUG:teuthology.misc::sh: openstack --quiet server show -f json 7805cbf2-6ade-4d21-9486-d36e067e20a9
2017-10-12T14:21:27.637 DEBUG:teuthology.misc:{
2017-10-12T14:21:27.637 DEBUG:teuthology.misc:"OS-EXT-STS:task_state": "spawning",
2017-10-12T14:21:27.637 DEBUG:teuthology.misc:"addresses": "",
2017-10-12T14:21:27.637 DEBUG:teuthology.misc:"image": "teuthology-sle-12.3-x86_64 (43111f30-1864-4b14-af08-1173bf015036)",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"OS-EXT-STS:vm_state": "error",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"OS-SRV-USG:launched_at": null,
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"flavor": "vps-ssd-3 (88372692-2157-42a2-855e-121374c7d759)",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"id": "7805cbf2-6ade-4d21-9486-d36e067e20a9",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"user_id": "0535b92544c74671a2a122b214a0025f",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"OS-DCF:diskConfig": "MANUAL",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"accessIPv4": "",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"accessIPv6": "",
2017-10-12T14:21:27.638 DEBUG:teuthology.misc:"OS-EXT-STS:power_state": "NOSTATE",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"project_id": "43583fef7b734bb1b6fb5f86d48abe5e",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"config_drive": "",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"status": "ERROR",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"updated": "2017-10-12T14:19:26Z",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"hostId": "33479b3a57b466ea652335aa8581b259361b5597e62478c267c4689b",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"OS-SRV-USG:terminated_at": null,
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"key_name": "teuth-kyr",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"properties": "ownedby='158.69.66.174', teuthology='eef6d328c92f825cad5f8927c3147b6f'",
2017-10-12T14:21:27.639 DEBUG:teuthology.misc:"OS-EXT-AZ:availability_zone": "nova",
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:"name": "target",
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:"created": "2017-10-12T13:48:57Z",
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:"fault": {
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:"message": "Build of instance 7805cbf2-6ade-4d21-9486-d36e067e20a9 aborted: Failed to allocate the network(s), not rescheduling.",
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:"code": 500,
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:"created": "2017-10-12T14:19:25Z"
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:},
2017-10-12T14:21:27.640 DEBUG:teuthology.misc:"os-extended-volumes:volumes_attached": []
2017-10-12T14:21:27.676 DEBUG:teuthology.misc:}
2017-10-12T14:21:27.677 ERROR:teuthology.provision.openstack:'get ip 7805cbf2-6ade-4d21-9486-d36e067e20a9' reached maximum tries (30) after waiting for 60 seconds
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/provision/openstack.py", line 165, in create
    ip = instance.get_ip(network)
  File "/home/ubuntu/teuthology/teuthology/openstack/__init__.py", line 147, in get_ip
    self.get_addresses())[0]
  File "/home/ubuntu/teuthology/teuthology/openstack/__init__.py", line 105, in get_addresses
    while proceed():
  File "/home/ubuntu/teuthology/teuthology/contextutil.py", line 132, in __call__
    raise MaxWhileTries(error_msg)
MaxWhileTries: 'get ip 7805cbf2-6ade-4d21-9486-d36e067e20a9' reached maximum tries (30) after waiting for 60 seconds
`

**Comment by kshtsk** [comment]
Interesting that logs for this DEAD job has not uploaded to the given log storage.

**Comment by smithfarm** [comment]
I have not seen this before. Is it happening on `master` ?

**Comment by kshtsk** [comment]
@smithfarm I think it is valid for _master_ too.
