### ISSUE TITLE
ceph-cm-salt occasionally fails because test.ping returns "No minions matched the target. No command was sent, no jid was assigned."

### ISSUE THREAD

**Issue by smithfarm** [SUSE/teuthology#85]
I've been using ceph-cm-salt intensively the past few days, and this has happened twice. The log says:

```
2017-06-14T07:33:07.010 INFO:teuthology.orchestra.run.target147135132145:Running: 'sudo systemctl restart salt-master.service'
2017-06-14T07:33:07.634 INFO:teuthology.orchestra.run.target149202188049:Running: 'sudo systemctl restart salt-minion.service'
2017-06-14T07:33:07.963 INFO:teuthology.orchestra.run.target149202188074:Running: 'sudo systemctl restart salt-minion.service'
2017-06-14T07:33:08.262 INFO:teuthology.orchestra.run.target147135132145:Running: 'sudo salt -C G@job_id:89 test.ping'
2017-06-14T07:33:08.740 INFO:teuthology.orchestra.run.target147135132145.stderr:[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
2017-06-14T07:33:08.740 INFO:teuthology.orchestra.run.target147135132145.stderr:[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
2017-06-14T07:33:08.799 INFO:teuthology.orchestra.run.target147135132145.stderr:[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
2017-06-14T07:33:08.799 INFO:teuthology.orchestra.run.target147135132145.stderr:[WARNING ] Key 'file_ignore_glob' with value None has an invalid type of NoneType, a list is required for this value
2017-06-14T07:33:12.381 INFO:teuthology.orchestra.run.target147135132145.stderr:ERROR: No return received
2017-06-14T07:33:12.501 INFO:teuthology.orchestra.run.target147135132145.stdout:No minions matched the target. No command was sent, no jid was assigned.
2017-06-14T07:33:12.502 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 86, in run_tasks
    manager = run_one_task(taskname, ctx=ctx, config=config)
  File "/home/ubuntu/teuthology/teuthology/run_tasks.py", line 65, in run_one_task
    return task(**kwargs)
  File "/home/ubuntu/teuthology/teuthology/task/ceph_cm_salt.py", line 16, in task
    salt.ping_minions()
  File "/home/ubuntu/teuthology/teuthology/salt.py", line 216, in ping_minions
    'test.ping'], len(self.remotes))
  File "/home/ubuntu/teuthology/teuthology/salt.py", line 198, in __ping
    self.master_remote.run(args=ping_cmd, stdout=output)
  File "/home/ubuntu/teuthology/teuthology/orchestra/remote.py", line 193, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/ubuntu/teuthology/teuthology/orchestra/run.py", line 403, in run
    r.wait()
  File "/home/ubuntu/teuthology/teuthology/orchestra/run.py", line 166, in wait
    label=self.label)
CommandFailedError: Command failed on target147135132145 with status 2: 'sudo salt -C G@job_id:89 test.ping'
```

**Comment by jan--f** [comment]
Sounds like the minions took their time to restart. Should we maybe run the ping in a short-ish retry loop?

**Comment by smithfarm** [comment]
We already are - see https://github.com/SUSE/teuthology/blob/master/teuthology/salt.py#L193-L203

The problem seems to be that the salt command returns non-zero status code in this rare case, so we would just need to suppress that. Easy fix.

**Comment by smithfarm** [comment]
Tested; works fine:

```
2017-06-14T18:21:23.785 INFO:teuthology.orchestra.run.target213032030188:Running: 'sudo su -c \'salt -C "G@job_id:8" test.ping || true\''
2017-06-14T18:21:40.714 INFO:teuthology.orchestra.run.target213032030188.stdout:target213032030188.teuthology:
2017-06-14T18:21:40.715 INFO:teuthology.orchestra.run.target213032030188.stdout:    Minion did not return. [No response]
2017-06-14T18:21:40.715 DEBUG:teuthology.salt:0 minion(s) responded
2017-06-14T18:21:45.716 INFO:teuthology.orchestra.run.target213032030188:Running: 'sudo su -c \'salt -C "G@job_id:8" test.ping || true\''
2017-06-14T18:21:46.452 INFO:teuthology.orchestra.run.target213032030188.stdout:target213032030188.teuthology:
2017-06-14T18:21:46.452 INFO:teuthology.orchestra.run.target213032030188.stdout:    True
2017-06-14T18:21:46.453 DEBUG:teuthology.salt:1 minion(s) responded
```
